name: examen-question-two
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
        
      - run: npm install
      - run: npm run build